AlcidesLaboratorio/AlcidesLaboratorio/Models/ErrorViewModel.cs
using System;

namespace AlcidesLaboratorio.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AlcidesLaboratorio/AlcidesLaboratorio/Models/Paciente.cs
using System;

namespace AlcidesLaboratorio.Models
{
    public class Paciente
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public DateTime DataNascimento { get; set; }
        public PlanoDeSaude PlanoDeSaude { get; set; }
    }
}

AlcidesLaboratorio/AlcidesLaboratorio/Models/PlanoDeSaude.cs
namespace AlcidesLaboratorio.Models
{
    public class PlanoDeSaude
    {
        public int PlanoDeSaudeId { get; set; }
        public string Descricao{ get; set; }
    }
}

AlcidesLaboratorio/AlcidesLaboratorio/Controllers/HomeController.cs
using AlcidesLaboratorio.Models;
using AlcidesLaboratorio.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;

namespace AlcidesLaboratorio.Controllers
{
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AlcidesLaboratorio/AlcidesLaboratorio/Controllers/PacientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AlcidesLaboratorio.Models;
using AlcidesLaboratorio.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AlcidesLaboratorio.Controllers
{
    public class PacientesController : Controller
    {
        private readonly PacienteServices pacienteServices;
        public PacientesController(PacienteServices pacienteServices)
        {
            this.pacienteServices = pacienteServices;
        }
        [HttpGet]
        public IActionResult Listar()
        {
            IList<Paciente> pacientes = pacienteServices.FindAll();
            return View(pacientes);
        }
        [HttpPost]
        public IActionResult Listar(IList<Paciente> pacientes)
        {
            return View(pacientes);
        }
        [HttpGet]
        public IActionResult Novo()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Novo(Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                pacienteServices.Insert(paciente);
                return RedirectToAction(nameof(Listar));
            }
            return View();

        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Paciente paciente = pacienteServices.FindById(id);
            return View(paciente);
        }
        [HttpPost]
        public IActionResult Delete(Paciente paciente)
        {
            pacienteServices.Delete(paciente);
            return RedirectToAction(nameof(Listar));
        }
        [HttpPost]
        public IActionResult Update(Paciente paciente)
        {
            pacienteServices.Update(paciente);
            return RedirectToAction(nameof(Listar));
        }
        public IActionResult Update(int id)
        {
            Paciente paciente = pacienteServices.FindById(id);
            return View(paciente);
        }
    }
}

AlcidesLaboratorio/AlcidesLaboratorio/Controllers/PlanoDeSaudeController.cs
using AlcidesLaboratorio.Models;
using AlcidesLaboratorio.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AlcidesLaboratorio.Controllers
{
    public class PlanoDeSaudeController : Controller
    {
        private readonly PlanoDeSaudeService planoDeSaudeService;
        public PlanoDeSaudeController(PlanoDeSaudeService planoDeSaudeService)
        {
            this.planoDeSaudeService = planoDeSaudeService;
        }
        [HttpGet]
        public IActionResult Listar()
        {
            IList<PlanoDeSaude> planos = planoDeSaudeService.FindAll();
            return View(planos);
        }
        [HttpPost]
        public IActionResult Listar(IList<PlanoDeSaude> planos)
        {
            return View(planos);
        }
        [HttpGet]
        public IActionResult Novo()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Novo(PlanoDeSaude planoDeSaude)
        {
            if (ModelState.IsValid)
            {
                planoDeSaudeService.Insert(planoDeSaude);
                return RedirectToAction(nameof(Listar));
            }
            return View();                                                                                                                         

        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
           PlanoDeSaude plano = planoDeSaudeService.FindById(id);
            return View(plano);
        }
        [HttpPost]
        public IActionResult Delete(PlanoDeSaude planoDeSaude)
        {
            planoDeSaudeService.Delete(planoDeSaude);
            return RedirectToAction(nameof(Listar));
        }
        [HttpPost]
        public IActionResult Update(PlanoDeSaude planoDeSaude)
        {
            planoDeSaudeService.Update(planoDeSaude);
            return RedirectToAction(nameof(Listar));
        }
        public IActionResult Update(int id)
        {
            PlanoDeSaude plano = planoDeSaudeService.FindById(id);
            return View(plano);
        }

    } 
}

AlcidesLaboratorio/AlcidesLaboratorio/Views/PlanoDeSaude/Delete.cshtml
@model AlcidesLaboratorio.Models.PlanoDeSaude

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PlanoDeSaude</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlanoDeSaudeId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlanoDeSaudeId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AlcidesLaboratorio/AlcidesLaboratorio/Views/PlanoDeSaude/Listar.cshtml
@model IEnumerable<AlcidesLaboratorio.Models.PlanoDeSaude>

@{
    ViewData["Title"] = "Listar";
}

<h2>Listar</h2>

<p>
    <a asp-action="Novo">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PlanoDeSaudeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
     
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlanoDeSaudeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>

}
    </tbody>
</table>

AlcidesLaboratorio/AlcidesLaboratorio/Views/PlanoDeSaude/Novo.cshtml
@model AlcidesLaboratorio.Models.PlanoDeSaude

@{
    ViewData["Title"] = "Novo";
}

<h2>Novo</h2>

<h4>PlanoDeSaude</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Novo">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PlanoDeSaudeId" class="control-label"></label>
                <input asp-for="PlanoDeSaudeId" class="form-control" />
                <span asp-validation-for="PlanoDeSaudeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success glyphicon glyphicon-plus" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlcidesLaboratorio/AlcidesLaboratorio/Views/PlanoDeSaude/Update.cshtml
@model AlcidesLaboratorio.Models.PlanoDeSaude

@{
    ViewData["Title"] = "Update";
}

<h2>Update</h2>

<h4>PlanoDeSaude</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PlanoDeSaudeId" class="control-label"></label>
                <input asp-for="PlanoDeSaudeId" class="form-control" />
                <span asp-validation-for="PlanoDeSaudeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlcidesLaboratorio/AlcidesLaboratorio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlcidesLaboratorio</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AlcidesLaboratorio</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="PlanoDeSaude" asp-action="Listar">Plano de Saude</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - AlcidesLaboratorio</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>